apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: password-generator
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      containers:
      - name: nginx
        image: password-generator:latest  # This should be the image name you've built and pushed to a registry (e.g., Docker Hub)
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-files
        hostPath:
          path: /path/to/your/local/project/folder  # The path to your local project folder
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: password-generator-service
spec:
  selector:
    app: password-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # This will expose the service externally if your Kubernetes setup supports LoadBalancer
